### ISSUE TITLE
Giá trị ngày  trong form

### ISSUE THREAD

**Issue by hpleduit** [hongoctrien/module-nvform#16]
Khi mình chọn mục giá trị ngày phần năm mặc định ban đầu nó chỉ hiển thị từ năm 2005 đến 2025, nếu người dùng họ không biết họ không chọn được năm nhỏ hơn ví dụ năm 1990 chẳng hạn, khi ta chọn năm nhỏ nhất 2005 thì mấy năm ở phía trước mới hiện ra  mình thấy điều này rất bất tiện ở đây phần chọn năm ta có thể liệt kê tất cả các năm để người dùng có thể chọn năm bất kỳ ...
Không biết điều này mình fix chổ nào cho nó hiện thị tất cả các năm không ạ. thanks!

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/module-nvform/commit/3e742df95e1334f157cfbe64aa851de6678d5767
