### ISSUE TITLE
Một số lỗi phát sinh

### ISSUE THREAD

**Issue by motcaiten** [hongoctrien/module-nvform#23]
Khi vào xem câu trả lời cho từng người thì bị lỗi 

![1](https://cloud.githubusercontent.com/assets/8292355/16804496/5bca59dc-4936-11e6-8aa8-85d8ce02c1fd.JPG)

Khi vào sửa biểu mẫu cũng phát sinh lỗi 

![2](https://cloud.githubusercontent.com/assets/8292355/16804497/5bca62e2-4936-11e6-9e62-6243427073e5.JPG)

**Comment by mynukeviet** [comment]
Fixed: https://github.com/hongoctrien/module-nvform/commit/b6557d930559ace3366981f55d6afeba81e04971
