### ISSUE TITLE
Vài đề xuất

### ISSUE THREAD

**Issue by thaotrinhj** [hongoctrien/module-nvform#7]
1- Các form online đề có trường text để có thể viết thêm một đoạn text trong form, mình đề nghị tác giả thêm kiểu text vào nữa.
2- Kiểu date hiện nay là dạng chuổi số, loại này tốt trong nhiều trường hợp nhưng trong trường hợp tùy biến trường dữ liệu thì việc xác định đâu là trường date để convert sang dạng DD/mm/yyyy có thể không khả thi. Do đó mình nghĩ cứ lưu date ở dạng thông thường cho tiện, dù sao thì số ký tự cũng ko đổi.
3- Cũng giống như tùy biến trường dữ liệu trong module user, cái này cũng có chút nhầm chính tả
<img src="https://camo.githubusercontent.com/ba3e6c8c8f67ddf2d324746a2b3c1e8909207832/687474703a2f2f692e696d6775722e636f6d2f6a755839706f702e706e67"/>
Cái này phải là số lớn nhất và số nhỏ nhất mới đúng.

**Comment by hongoctrien** [comment]
Mình xin ghi nhận ạ. Song do tgian đang hạn hẹp nên chưa thể fix ngay được. ^^

**Comment by dtsoncntt** [comment]
Mỗi form có 1 template riêng để có thể tùy biến teamplate cho các form
Mỗi form sinh ra 1 mã code để có thể đưa vào hiển thị trong bài viết
Mỗi form có 1 cấu hình email để có thể gửi nội dung tới từng email khác nhau.
Thêm 1 trường text title
Tạm thế đã ....

**Comment by hongoctrien** [comment]
> 1- Các form online đề có trường text để có thể viết thêm một đoạn text trong form, mình đề nghị tác giả thêm kiểu text vào nữa.

Cái này là sao ý @thaotrinhj nhỉ. Có phải là câu hỏi dạng text (textarea, editor) không bạn?

**Comment by hongoctrien** [comment]
> 1- Các form online đề có trường text để có thể viết thêm một đoạn text trong form, mình đề nghị tác giả thêm kiểu text vào nữa.

Đã thêm dữ liệu plaintext https://github.com/hongoctrien/module-nvform/commit/d873258d0bba343a7eb59fd3d84667109db76b5e

> 2- Kiểu date hiện nay là dạng chuổi số, loại này tốt trong nhiều trường hợp nhưng trong trường hợp tùy biến trường dữ liệu thì việc xác định đâu là trường date để convert sang dạng DD/mm/yyyy có thể không khả thi. Do đó mình nghĩ cứ lưu date ở dạng thông thường cho tiện, dù sao thì số ký tự cũng ko đổi.

Dựa vào trường question_type để phân biệt loại câu hỏi, còn dữ liệu này không liên quan gì hết bạn. Mình thấy lưu dạng số dễ làm việc, dễ thống kê hơn dạng date.

> 3- Cũng giống như tùy biến trường dữ liệu trong module user, cái này cũng có chút nhầm chính tả

Đã cập nhật https://github.com/hongoctrien/module-nvform/commit/7b1c1e4ba822ec86b9f77252dbfa8f6c418bf8df
